language: node_js
os:
  - linux
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - "10"
  # - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - lts/*
  - node
cache:
  directories:
    - node_modules
jobs:
  include:
    - name: test-sonar
      script: sonar-scanner
      node_js: 12
      if: branch = 'master'
    - name: deploy-docs
      script: bash ./.scripts/travis-publish-docs.sh nestjs-metrics
      node_js: 12
      if: |
        branch = 'master' AND
        NOT commit_message =~ /^chore: release/
    - name: deploy-code
      script: bash ./.scripts/travis-release-it.sh
      node_js: 12
      deploy:
        provider: npm
        email: dragos.cirjan@gmail.com
        api_key: Y1e8p5HgFk/VDVM1KaitRLM0EFnd2TcRlEhJF4JZ2v/sTKMPLYOKXaPnG7KFJ72wn/FvJG/Bf4Vt0Bmk+lRBV4POLizvUra252TEbQXJiLAmBTBM+2Rl+p6eVScnZz2hNZKFypHWF69Vim/Mz9sy63orZ6XUgKKJPb7N4KLAOAegO61tE+9/qGIMMX1tKHed7zJmMLay9ESgef6fT8eRIq04kfN4iQxnEpAz3jj04aHn7sfRVV4rSYbsoArAQTyByAQsUtXFdS9y50Fj/pwVxQiRvuGyOG/fg6rtKcKcK3w6+N+S082Pg4rpXBgGaLk77go/DbsH8LkAMDiHgfjaMstocI3ApHNz0Cm4hDHlRPXiYbSIp7MXiBijknFYWb5dWACcIoipFZHbAHwpI0H8e9ZD/F45vgPW/eTHoIE/T6I1RgmX9AkOVX37gTpSv5rBiynygDPXCGV9XAOXdmf9kAdjyMy5vDzzs40B22xL3DvzVVv7OhBHxhK7ItQ1JN0LelSaOR9gTl5ReYwNp1JXiemJtmvbhA8oUvkaULrtVN6oMtHlB8603133c/MWtNKWGot4D6dE0UPpozJD/O4SEKaXJoD/cgPSH9XU4sLXBV1LPGnYheNK2nD3lffKQyqAL16VP+FO/OzNBlmZMhGW7l4dy4qCcPWGZ7S0CeCHXRc=
      if: |
        branch = 'master' AND
        NOT commit_message =~ /^chore: release/
scripts:
  - set -e
  - npm i
  - npm run bootstrap
  - npm run prettier:write
  # - npm run lint:write
  - npm run jscpd
  # - npm run depcruise
  - npm run test
  # - npm run build
after_script:
  - bash ./.scripts/travis-telegram-report.sh
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "mists-aside"
    token:
      secure: "LvXzdsDUR+PXvtsRC1S7z/Chv+yn8VPzG6wOf7VWIOJw7CfM5jvWDC6WhPxkcyP/APslhE8ZOdKfWrZoeJjCA82jRJQZb0Uu7Ry6FRfq8Rd1zaeJWs7cRU0FrSbOuqDfDNgDndbYBmbVUIr9WgqLbevN+tREDsn9Z71Gm7ehN67L9Mc5wPT7VIbAe1XTmYpYWknHkyMmy7nlXOUKdNWt67y/JHqKRQG+dE6370ipqBb/0bsiGUS5UctIJl4zqTPTZrgqpXjx3dakL3qI0lNcFecTira/u1wYpYE+rdKZ/TfE/Feh+Pz5gU8lQ8BeCXlJ1pGlf4hBjuSqbEpmo4k/OMhgi4wcqlEsPKF3Dtiq3aS53fp4wc0WDTY8+owsfArCN7KYb+h7GMaz5mCK8zBYdNmCvZ/OQpem6wYQE+mlKuucE11xc/kkjzdpImx36r3+cscJWu+1HcBjSWNBvvVdlwx/de5u+4y7rp4j5aHD2Npz74ylsvxMNE4ajDNyggs/b7EhrCU00xepUrS5voU+1S1MJe8HrXcyDj+u8yFECnTXg50SLL2kpfTzxEzjxof02VcKEQsXFTPTo2xAAJEThNXz5SRvuFsZHQLk4+oFdFKrrcaWJeAUkVLris1xIfQf1zfuwlt0g9r4ITiZo0PoRAV+krT4UjSml1FBE32uYH4="
