language: node_js
os:
  - linux
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - "10"
  # - "11"
  - "12"
  - "13"
  - "14"
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
scripts:
  - set -e
  - npm i
  - npm run prettier:write
  - npm run lint:write
  - npm run jscpd
  - npm run depcruise
  - npm run test
  - npm run test:junit
  # - npm run build
# after_script:
  - if [[ $TRAVIS_NODE_VERSION == '12' ]]; then npm run docs; fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "mists-aside"
    token:
      secure: "c5w34vDkFA8ErdN0Z/YkXB0S9frD4iPcle5R2cT/gpNXoaUOY1I25RfmUU4oOkZ9bPpnTajiGC1GX0/ky7xdl7dW4Am0LJnuuhejONz1hqwWAhIT/47g4jVjlujBdDUdP1/fGRBi1htxNsEA4e1mkYIcpS7ee8MwrTMBdukr51viwoBHPT0Pw0CQNTmdUGnnapPPLlXmCim5Is3Df9EmhN7QExlZoc60eKZjINHXqoPSEWmCEXhfoOrULRgiuKHIehcBtyQoQs2Rg5KVxdKzJmZu22lrBZiL+cJ6QjK4NFiK6zW1Hh71Vg+TncqD/9uj7Gk7e/feaUerM9yx8391Zu7F0q1QCNsO6p7veptNXcfsREu2pkfPeOictKVRdw0RS2FvPL2laGToRkjApbhOKJtIYV2bkJkasQ4QPqKvJA4z+haFWOmD89AL8+OfdG0PU0U3kxvxjpUucmmQeqcBZukjUDnZgnfDnwnND7al3D6tTfXQsYX4+oTi3T6uQnDWEixp9JAS7kO9WfGpTmDIvzSb8Oij9G1UfNnVD2n9vf3bmCuJxA0ksWOA5TohXRBZ1KpGXMzsufZfTJ+Ee2eQdNLk5RZ8MJ5jH5aX1xIujcegvd5MToaUVju9ZVLeW1hUJa6+j8uLuaVQKF7vsl357r+gmUYruD0FMrlmhG7ePPU="
