language: node_js
os:
  - linux
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - "10"
  # - "11"
  - "12"
  - "13"
  - "14"
  - lts/*
  - node
cache:
  directories:
    - node_modules
scripts:
  - set -e
  - npm i
  - npm run prettier:write
  - npm run lint:write
  - npm run jscpd
  - npm run depcruise
  - npm run test
  - npm run build
after_script:
  - if [[ $TRAVIS_NODE_VERSION == '12' ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    sonar-scanner;
    if [[ "$TRAVIS_BRANCH" == "develop" ]]; then bash ./.scripts/publish-docs.sh nestjs-metrics; fi;
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run release -- patch; npm publish; fi;
    fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "mists-aside"
    token:
      secure: "LvXzdsDUR+PXvtsRC1S7z/Chv+yn8VPzG6wOf7VWIOJw7CfM5jvWDC6WhPxkcyP/APslhE8ZOdKfWrZoeJjCA82jRJQZb0Uu7Ry6FRfq8Rd1zaeJWs7cRU0FrSbOuqDfDNgDndbYBmbVUIr9WgqLbevN+tREDsn9Z71Gm7ehN67L9Mc5wPT7VIbAe1XTmYpYWknHkyMmy7nlXOUKdNWt67y/JHqKRQG+dE6370ipqBb/0bsiGUS5UctIJl4zqTPTZrgqpXjx3dakL3qI0lNcFecTira/u1wYpYE+rdKZ/TfE/Feh+Pz5gU8lQ8BeCXlJ1pGlf4hBjuSqbEpmo4k/OMhgi4wcqlEsPKF3Dtiq3aS53fp4wc0WDTY8+owsfArCN7KYb+h7GMaz5mCK8zBYdNmCvZ/OQpem6wYQE+mlKuucE11xc/kkjzdpImx36r3+cscJWu+1HcBjSWNBvvVdlwx/de5u+4y7rp4j5aHD2Npz74ylsvxMNE4ajDNyggs/b7EhrCU00xepUrS5voU+1S1MJe8HrXcyDj+u8yFECnTXg50SLL2kpfTzxEzjxof02VcKEQsXFTPTo2xAAJEThNXz5SRvuFsZHQLk4+oFdFKrrcaWJeAUkVLris1xIfQf1zfuwlt0g9r4ITiZo0PoRAV+krT4UjSml1FBE32uYH4="
